[WIP]11.0_mig_l10n_ch_pain_base
OCA/l10n-switzerland pull request #384
Opened 2017-12-12 15:00 UTC by mpanarin

Migartion of l10n_ch_pain_base to odoo 11.
As it is not mentioned in migration guidelines, should i change super calls to the python3 way?
aka
super().create(vals) vs super(foobar, self).create(vals)

2017-12-14 08:07 UTC, simahawk requested changes

2017-12-14 08:07 UTC, simahawk commented on l10n_ch_pain_base/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/125/9.0
/9.0 -> /11.0 (sounds like branch 10.0 should be fixed too)

2017-12-14 08:07 UTC, simahawk commented on l10n_ch_pain_base/__manifest__.py
> +    "version": "11.0.1.0.1",
11.0.1.0.0

2017-12-14 08:07 UTC, simahawk commented on l10n_ch_base_bank/i18n/de.po
> +"Project-Id-Version: Odoo Server 11.0\n"
I'm not sure we should pull these changes... I'd expect them to be already in v11. @yvaucher ?

2017-12-18 08:08 UTC, simahawk commented
@mpanarin rebase pls. @yvaucher ping :)

2017-12-20 16:36 UTC, yvaucher requested changes
For the renaming see:

https://github.com/OCA/l10n-switzerland/pull/387/files#diff-09fc31143adcd8e571fdc21d563dbe36

2017-12-20 16:36 UTC, yvaucher commented on l10n_ch_pain_base/i18n/en.po
> +# Translation of Odoo Server.
This file can be removed

2017-12-20 16:36 UTC, yvaucher commented on l10n_ch_pain_base/i18n/nb_NO.po
> +# Translation of Odoo Server.
This file to remove from the OCA translation commit

2017-12-20 16:36 UTC, yvaucher commented on l10n_ch_pain_base/models/account_payment_order.py
> +                    "For pain.001.001.03.ch.02, for non-BVR payments, "
Please rename non-BVR to non-ISR

2017-12-20 16:36 UTC, yvaucher commented on l10n_ch_pain_base/models/account_payment_line.py
> +    communication_type = fields.Selection(selection_add=[('bvr', 'BVR')])
It would be great if you could change this value to `isr` and create an Openupgrade scrpt to change all `bvr` values to `isr`

2017-12-20 16:36 UTC, yvaucher commented on l10n_ch_pain_base/models/account_payment_order.py
> +        # BVR orders cannot be SEPA orders
s/BVR/ISR

2017-12-20 16:36 UTC, yvaucher commented on l10n_ch_pain_base/models/account_payment_order.py
> +                # Don't set the creditor agent on BVR/CH01 payments
s/BVR/ISR

2017-12-20 16:36 UTC, yvaucher commented on setup/l10n_ch_base_bank/odoo/__init__.py
> -__import__('pkg_resources').declare_namespace(__name__)
I don't think this was intented to remove this file

2017-12-20 16:36 UTC, yvaucher commented on setup/l10n_ch_pain_base/odoo/addons/l10n_ch_pain_base
> +../../../../l10n_ch_pain_base
You don't need to edit the setup directory, we have a bot for that.

2018-02-01 15:40 UTC, grindtildeath approved these changes
Code review only 👍

2018-04-04 11:55 UTC, tschanzt approved these changes
Looks good.

2018-04-05 09:00 UTC, asaunier commented
Suggested changes seem to have been done. @yvaucher @simahawk do you approve the PR now?

2018-04-05 09:52 UTC, simahawk approved these changes
approving but check and remove the oca_dep if not needed

2018-04-05 09:52 UTC, simahawk commented on oca_dependencies.txt
> +l10n-switzerland https://github.com/yvaucher/l10n-switzerland 11.0-mig-rename-bvr-to-isr
we should drop this, isnt't it?

2018-04-06 08:36 UTC, yvaucher approved these changes

2018-04-06 08:36 UTC, merged