[ADD] line.communication of paiement even if it's not a bvr reference
OCA/l10n-switzerland pull request #436
Opened 2018-07-26 06:45 UTC by vrenaville

2018-07-26 06:46 UTC, nbessi approved these changes
LGTM seems legit

2018-07-26 06:47 UTC, CharlineDumontet approved these changes

2018-07-26 13:58 UTC, yvaucher requested changes

2018-07-26 13:58 UTC, yvaucher commented on l10n_ch_sepa/l10n_ch/template/pain.001.001.03.ch.02.xml.mako
> +    <Strd>
Strd is for structured references only. I don't think we should passe a free reference that way.

2018-07-26 14:58 UTC, yvaucher commented on l10n_ch_sepa/l10n_ch/template/pain.001.001.03.ch.02.xml.mako
> +    <Strd>
Ok it must be BVR only for type 1 which is what was implemented.

For other types, it is a structured reference like ISO 11649, QR or IPI. 

Page 44
https://www.six-interbank-clearing.com/dam/downloads/fr/standardization/iso/swiss-recommendations/implementation-guidelines-ct.pdf

```
2.126 Ref:

Type 1: Doit contenir le numéro de référence BVR.
Type 5: Doit être 
utilisée si «Creditor Reference
Information» est utilisé, peux contenir «Creditor
Reference» conformément à ISO 11649.
Autres types: Références structurées, par exemple
référence ISO (ISO 11649) ou référence QR ou
référence IPI.
Remarque: Le justificatif I
PI doit être retiré de la
circulation au plus tard le 31.03.2020.
```

More information about reference on page 46

2018-08-15 08:35 UTC, vrenaville commented
@yvaucher 

You are right, I will check to add a free reference.

Vincent

2018-08-15 08:35 UTC, closed without merging