[14.0][FIX] l10n_ch_base_bank tests
OCA/l10n-switzerland pull request #609
Opened 2021-07-21 14:45 UTC by SimoneVagile

2021-07-22 09:42 UTC, SimoRubi requested changes

2021-07-22 09:42 UTC, SimoRubi commented on l10n_ch_base_bank/tests/test_create_invoice.py
> -    def test_emit_move_with_isr_ref_missing_subscr_num(self):
Why have you removed this test?

2021-08-23 12:30 UTC, leemannd commented on l10n_ch_base_bank/tests/test_create_invoice.py
> +        inv_form.save()
What is the reason to trigger twice in a row `inv_form.save()`

2021-08-24 13:50 UTC, SimoRubi requested changes

2021-08-24 13:50 UTC, SimoRubi commented on l10n_ch_base_bank/tests/test_create_invoice.py
> +        cls.bank_acc = cls.env["res.partner.bank"].create(
This variable is not used anywhere, why is it needed?

2021-08-24 13:50 UTC, SimoRubi commented on l10n_ch_base_bank/tests/test_create_invoice.py
> +                "type": "sale",
Please update the variable name too: it can be confusing to have now a `bank_journal` of type `sale`

2021-08-24 13:50 UTC, SimoRubi commented on l10n_ch_base_bank/tests/test_create_invoice.py
> +        inv_form.save()
See https://github.com/OCA/l10n-switzerland/pull/609/files#r693927513

2021-08-24 15:19 UTC, SimoneVagile commented on l10n_ch_base_bank/tests/test_create_invoice.py
> +        cls.bank_acc = cls.env["res.partner.bank"].create(
It's the partner bank account reported from partner to invoice (move).

See [https://github.com/odoo/odoo/blob/14.0/addons/account/models/account_move.py#L1311](https://github.com/odoo/odoo/blob/14.0/addons/account/models/account_move.py#L1311) and [https://github.com/odoo/odoo/blob/14.0/addons/account/models/account_move.py#L464](https://github.com/odoo/odoo/blob/14.0/addons/account/models/account_move.py#L464)

2021-08-25 13:28 UTC, SimoRubi requested changes

2021-08-25 13:28 UTC, SimoRubi commented on l10n_ch_base_bank/tests/test_create_invoice.py
> +        cls.bank_acc = cls.env["res.partner.bank"].create(
> See https://github.com/odoo/odoo/blob/14.0/addons/account/models/account_move.py#L1311 and 

The move's `bank_partner_id` is set to the company's partner.

> https://github.com/odoo/odoo/blob/14.0/addons/account/models/account_move.py#L464

The move's `partner_bank_id` is set to previously set partner's bank account.

That does not answer to why is this variable needed or why do you have to create a `res.partner.bank` when it was not needed in `12.0`, could you please motivate that?

2021-08-25 13:28 UTC, SimoRubi commented on l10n_ch_base_bank/tests/test_create_invoice.py
> +                "type": "sale",
See https://github.com/OCA/l10n-switzerland/pull/609/files#r694796173

2021-08-26 10:35 UTC, SimoRubi requested changes
Please fix the commit history, currently there are 2 commits:

- `[14.0][FIX] l10n_ch_base_bank: drop test missing subscription` that removes a test
- `[FIX] tests` that restores the removed test and does also other things

Maybe the first commit can be removed and the second commit deserves a more meaningful commit message, see https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message:

> [...]
> Always put meaningful commit messages
> [...]

2021-08-26 10:35 UTC, SimoRubi commented on l10n_ch_base_bank/tests/test_create_invoice.py
> +        cls.env["res.partner.bank"].create(
From https://github.com/OCA/l10n-switzerland/pull/609#discussion_r695716509:
> why do you have to create a `res.partner.bank` when it was not needed in 12.0?

2021-08-26 15:23 UTC, SimoneVagile commented on l10n_ch_base_bank/tests/test_create_invoice.py
> +        cls.env["res.partner.bank"].create(
[https://github.com/OCA/l10n-switzerland/pull/603](https://github.com/OCA/l10n-switzerland/pull/603)

2021-08-26 15:39 UTC, SimoneVagile commented on l10n_ch_base_bank/tests/test_create_invoice.py
> +        cls.env["res.partner.bank"].create(
maybe i must cherry-pick [these](https://github.com/OCA/l10n-switzerland/pull/603/commits)?

2021-08-26 16:05 UTC, SimoRubi requested changes

2021-08-26 16:05 UTC, SimoRubi commented on l10n_ch_base_bank/tests/test_create_invoice.py
> +        cls.env["res.partner.bank"].create(
yes that would be better since here you basically have the same code

2021-08-27 09:18 UTC, SimoRubi requested changes

2021-08-27 09:18 UTC, SimoRubi commented on l10n_ch_base_bank/tests/test_create_invoice.py
> +        cls.env["res.partner.bank"].create(
Looks like the cherry-picked commit by itself is enough for the tests to be fixed, can you check that?
If so, you can drop your modifications and we will be simply aligned to `13.0`

2021-08-27 10:37 UTC, SimoRubi approved these changes

2021-09-13 11:47 UTC, leemannd approved these changes
Seems legit. Thanks

2021-09-23 14:46 UTC, SimoRubi commented
@OCA/local-switzerland-maintainers can this be merged?
Thanks!

2021-10-12 08:12 UTC, TDu commented
This one can be closed as https://github.com/OCA/l10n-switzerland/pull/616 has been merged and the 14 branch is green now
@yvaucher

2021-10-12 16:37 UTC, yvaucher commented
Thus closing it

2021-10-12 16:37 UTC, closed without merging

2021-10-12 16:38 UTC, yvaucher commented
@SimoneVagile thanks for the fix. Hope the other one is fine by you.

2022-03-02 14:30 UTC, SimoneVagile commented
> @SimoneVagile thanks for the fix. Hope the other one is fine by you.

I still have an error in Travis, see [https://github.com/OCA/l10n-switzerland/pull/591](https://github.com/OCA/l10n-switzerland/pull/591)

```
Traceback (most recent call last):

File "/home/travis/build/OCA/l10n-switzerland/setup/l10n_ch_base_bank/odoo/addons/l10n_ch_base_bank/tests/test_create_invoice.py", line 55, in test_emit_move_with_isr_ref

inv_form.save()

File "/home/travis/odoo-14.0/odoo/tests/common.py", line 1892, in save

r.write(values)

File "/home/travis/odoo-14.0/addons/account/models/account_move.py", line 2015, in write

res = super(AccountMove, self.with_context(check_move_validity=False, skip_account_move_synchronization=True)).write(vals)

File "/home/travis/odoo-14.0/addons/mail/models/mail_thread.py", line 316, in write

return super(MailThread, self).write(values)

File "/home/travis/odoo-14.0/addons/mail/models/mail_activity.py", line 788, in write

return super(MailActivityMixin, self).write(vals)

File "/home/travis/odoo-14.0/odoo/models.py", line 3693, in write

real_recs._validate_fields(vals, inverse_fields)

File "/home/travis/odoo-14.0/odoo/models.py", line 1266, in _validate_fields

check(self)

File "/home/travis/build/OCA/l10n-switzerland/setup/l10n_ch_base_bank/odoo/addons/l10n_ch_base_bank/models/invoice.py", line 83, in _check_bank_type_for_type_isr

"Bank account shouldn't be empty, for ISR ref"

odoo.exceptions.ValidationError: Bank account shouldn't be empty, for ISR ref type, you can set it manually or set appropriate payment mode.
```

Can you re-open this?