[14.0] [MIG] l10n_ch_invoice_reports: Migrate to version 14.0
OCA/l10n-switzerland pull request #620
Opened 2021-09-30 08:56 UTC by sonhd91

2021-10-07 07:06 UTC, sebalix requested changes

2021-10-07 07:06 UTC, sebalix commented on l10n_ch_invoice_reports/data/reports.xml
> +        <field name="attachment_use">True</field>
The previous value was `attachment_use="False"`, so:
```suggestion
        <field name="attachment_use" eval="False"/>
```

2021-10-07 07:06 UTC, sebalix commented on l10n_ch_invoice_reports/data/reports.xml
> +        <field name="attachment_use">False</field>
```suggestion
        <field name="attachment_use" eval="False"/>
```

2021-10-07 07:06 UTC, sebalix commented on l10n_ch_invoice_reports/data/reports.xml
> +        <field name="attachment_use">False</field>
```suggestion
        <field name="attachment_use" eval="False"/>
```

2021-10-07 07:06 UTC, sebalix commented on l10n_ch_invoice_reports/models/report.py
> +            )
I'm not sure to understand this piece of code? Have you some info about this?
I don't think having this kind of data updates in the method `_render_qweb_pdf` is a good idea.

2021-10-07 07:23 UTC, sonhd91 commented on l10n_ch_invoice_reports/data/reports.xml
> +        <field name="attachment_use">True</field>
Thanks for review, the branch was updated

2021-10-07 07:23 UTC, sonhd91 commented on l10n_ch_invoice_reports/data/reports.xml
> +        <field name="attachment_use">False</field>
Thanks for review, the branch was updated

2021-10-07 07:24 UTC, sonhd91 commented on l10n_ch_invoice_reports/data/reports.xml
> +        <field name="attachment_use">False</field>
Thanks for review, the branch was updated

2021-10-07 07:37 UTC, sonhd91 commented on l10n_ch_invoice_reports/models/report.py
> +            )
Thanks for review, I'm looking into it

2021-10-08 07:56 UTC, mmequignon approved these changes

2021-10-12 12:36 UTC, TDu approved these changes

2021-10-13 13:10 UTC, sebalix approved these changes

2021-10-15 06:37 UTC, simahawk commented
/ocabot merge nobump

2021-10-15 07:48 UTC, merged